### ISSUE TITLE
provide an admin GUI

### ISSUE THREAD

**Issue by s-friedman** [openfrontier/openldap-docker#1]
It would be very convenient to have an admin GUI such as phpldapadmin integrated into the openldap server.

**Comment by thinkernel** [comment]
https://github.com/shivshav/openldap-docker
This project is a fork of my project. They added a phpldapadmin. You may try it.

**Comment by s-friedman** [comment]
Thanks.  I see that he has some useful patches on a couple of the other sub-projects as well.
